### ISSUE TITLE
BOM in plain text for both PCBs?

### ISSUE THREAD

**Issue by KenjiUmino** [LimeProgramming/USB-serial-mouse-adapter#2]
I would like to build the slim version of this adapter, but I could not find a bill of materials list - until I looked into the KiCad files for the phat PCB and found a "BOM_JLCSMT.xls" that I had to download before I could view it.

This file seems to be for the slim PCB as it does not include the switch block.

It would be nice to have a BOM for both PCBs in plain text so it is viewable from the webbrowser.

**Comment by LimeProgramming** [comment]
Hello there

The slim PCB doesn't have the switch block at all. Honestly even though at first I was very amendment about the switch block being a requirement for ease of use, I use the terminal to configure the adapter. 

Fair point. I saved the BOM and CPL in normal excel file formats just to stop a popup when I saved the file in excel. 
I should be able to just add a readme in the folders. 

I hope you enjoy the adapter.

**Comment by KenjiUmino** [comment]
Hi Lime,

thanks a bunch for looking into it

> I saved the BOM and CPL in normal excel file formats just to stop a popup when I saved the file in excel.
> I should be able to just add a readme in the folders.

Thanks for looking into it - I have not finished the adapter yet, which might be a good thing, as I found out I might get it done cheaper than expected.

I originally planned to order the slim PCB at some PCB place, but in another futile attempt to organize the mancave, I found out that I have way too many of these small green proto boards than I know what to do with and it looks like they are just big enough to fit everything (including the jumpers for configuration) while the whole thing would be about the same size as a slim PCB.

![photo_2023-06-04_23-42-29](https://github.com/LimeProgramming/USB-serial-mouse-adapter/assets/85372551/c5e6d3e4-4274-4031-aabc-32e8d29e60b7)
